### ISSUE TITLE
too much jQuery

### ISSUE THREAD

**Issue by kounelios13** [fotisoikonomou/simple-cash#1]
Καλησπέρα
Σε κάθε σελίδα βαζεις ενα script που κατεβαζει το jQuery.Γιατί?Αφού δεν χρησιμοποιείς καθόλου jquery στον κωδικα σου?

**Comment by fotisoikonomou** [comment]
Καλησπέρα και σε ευχαριστώ πολύ για την παρατήρηση σου.
Έχεις δίκιο απλά ξεχάστηκε εκεί...δεν έχει λόγω ύπαρξης...και θα το σβησω

**Comment by fotisoikonomou** [comment]
The error is corrected
